# initialization

In [30]:
import numpy as np

Vector

In [31]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

Matrix

In [32]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

Initialize matrix

In [33]:
np.zeros([2,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [34]:
np.ones([2,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [37]:
np.random.permutation(5)

array([1, 0, 2, 4, 3])

# Reshape

Print matrix shape information

In [38]:
m = np.random.permutation(10)
m, m.shape

(array([9, 2, 5, 4, 7, 0, 6, 3, 1, 8]), (10,))

Reshape

In [39]:
m1 = m.reshape(2,5)
m1

array([[9, 2, 5, 4, 7],
       [0, 6, 3, 1, 8]])

In [40]:
m1.shape

(2, 5)

Vector -> Matrix

In [41]:
m[:,np.newaxis]

array([[9],
       [2],
       [5],
       [4],
       [7],
       [0],
       [6],
       [3],
       [1],
       [8]])

In [42]:
m[np.newaxis, :]

array([[9, 2, 5, 4, 7, 0, 6, 3, 1, 8]])

Concatenation

In [43]:
v1 = np.arange(0,4)  # [0, 1, 2, 3]
v2 = np.arange(6,10) # [6, 7, 8, 9]

m1 = v1.reshape(2,2) # [0, 1]
                     # [2, 3]

m2 = v2.reshape(2,2) # [6, 7]
                     # [8, 9]

In [44]:
np.hstack([v1[:,np.newaxis],v2[:,np.newaxis]])

array([[0, 6],
       [1, 7],
       [2, 8],
       [3, 9]])

In [45]:
np.vstack([v1,v2])

array([[0, 1, 2, 3],
       [6, 7, 8, 9]])

In [46]:
np.hstack([m1,m2])

array([[0, 1, 6, 7],
       [2, 3, 8, 9]])

In [47]:
np.vstack([m1,m2])

array([[0, 1],
       [2, 3],
       [6, 7],
       [8, 9]])

# Operation

Eltwise operation

In [48]:
m1 = np.ones([2,2])*3        # [3 3]
                             # [3 3]
m2 = np.array([[2,3],[4,5]]) # [2 3]
                             # [4 5]

In [49]:
m1 + m2

array([[ 5.,  6.],
       [ 7.,  8.]])

In [50]:
m1 - m2

array([[ 1.,  0.],
       [-1., -2.]])

In [51]:
m1 * m2

array([[  6.,   9.],
       [ 12.,  15.]])

In [52]:
m1 * 2

array([[ 6.,  6.],
       [ 6.,  6.]])

In [53]:
m1 / m2

array([[ 1.5 ,  1.  ],
       [ 0.75,  0.6 ]])

In [54]:
m1 / 2

array([[ 1.5,  1.5],
       [ 1.5,  1.5]])

Inner product

In [55]:
np.dot(m1,m2)

array([[ 18.,  24.],
       [ 18.,  24.]])

Inverse matrix

In [56]:
inv = np.linalg.pinv(m2)
inv

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [57]:
np.round(np.dot(m2, inv),2)

array([[ 1., -0.],
       [ 0.,  1.]])

In [58]:
np.round(np.dot(inv, m2),2)

array([[ 1.,  0.],
       [-0.,  1.]])