# initialization

In [1]:
import numpy as np

Vector

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

Matrix

In [3]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

Initialize matrix

In [4]:
np.zeros([2,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [5]:
np.ones([2,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [8]:
np.random.permutation(5)

array([2, 3, 0, 1, 4])

# Reshape

Print matrix shape information

In [9]:
m = np.random.permutation(10)
m, m.shape

(array([9, 4, 2, 5, 7, 0, 3, 8, 1, 6]), (10,))

Reshape

In [10]:
m1 = m.reshape(2,5)
m1

array([[9, 4, 2, 5, 7],
       [0, 3, 8, 1, 6]])

In [11]:
m1.shape

(2, 5)

Vector -> Matrix

In [12]:
m[:,np.newaxis]

array([[9],
       [4],
       [2],
       [5],
       [7],
       [0],
       [3],
       [8],
       [1],
       [6]])

In [13]:
m[np.newaxis, :]

array([[9, 4, 2, 5, 7, 0, 3, 8, 1, 6]])

Concatenation

In [14]:
v1 = np.arange(0,4)  # [0, 1, 2, 3]
v2 = np.arange(6,10) # [6, 7, 8, 9]

m1 = v1.reshape(2,2) # [0, 1]
                     # [2, 3]

m2 = v2.reshape(2,2) # [6, 7]
                     # [8, 9]

In [15]:
np.hstack([v1[:,np.newaxis],v2[:,np.newaxis]])

array([[0, 6],
       [1, 7],
       [2, 8],
       [3, 9]])

In [16]:
np.vstack([v1,v2])

array([[0, 1, 2, 3],
       [6, 7, 8, 9]])

In [17]:
np.hstack([m1,m2])

array([[0, 1, 6, 7],
       [2, 3, 8, 9]])

In [18]:
np.vstack([m1,m2])

array([[0, 1],
       [2, 3],
       [6, 7],
       [8, 9]])

# Operation

Eltwise operation

In [19]:
m1 = np.ones([2,2])*3        # [3 3]
                             # [3 3]
m2 = np.array([[2,3],[4,5]]) # [2 3]
                             # [4 5]

In [20]:
m1 + m2

array([[ 5.,  6.],
       [ 7.,  8.]])

In [21]:
m1 - m2

array([[ 1.,  0.],
       [-1., -2.]])

In [22]:
m1 * m2

array([[  6.,   9.],
       [ 12.,  15.]])

In [23]:
m1 * 2

array([[ 6.,  6.],
       [ 6.,  6.]])

In [24]:
m1 / m2

array([[ 1.5 ,  1.  ],
       [ 0.75,  0.6 ]])

In [25]:
m1 / 2

array([[ 1.5,  1.5],
       [ 1.5,  1.5]])

Inner product

In [26]:
np.dot(m1,m2)

array([[ 18.,  24.],
       [ 18.,  24.]])

Inverse matrix

In [27]:
inv = np.linalg.pinv(m2)
inv

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [28]:
np.round(np.dot(m2, inv),2)

array([[ 1., -0.],
       [ 0.,  1.]])

In [29]:
np.round(np.dot(inv, m2),2)

array([[ 1.,  0.],
       [-0.,  1.]])

#  Random

uniform random

In [30]:
np.random.rand()    # 1 random
np.random.rand(5)   # 5 random
np.random.rand(2,2) # 2x2 random matrix
np.random.rand(2,2) * 100

array([[ 77.31795766,  39.91202836],
       [ 51.7406963 ,  81.20402346]])

interger random

In [31]:
np.random.randint(100)                 # one 0-100 random data
np.random.randint(10, 30)              # one 10-30 random data
np.random.randint(10, 30, 5)           # five 10-30 random data
np.random.randint(10, 300, (2,2))      # 2x2 10-30 random matrix

array([[ 12, 236],
       [ 98, 120]])

normal random (gaussian random)

In [32]:
np.random.randn()         # mu 0, stddev 1
np.random.randn(10)       # mu 0, stddev 1 x 10
np.random.randn(10,10)    # mu 0, stddev 1 x (10 x 10)

np.random.normal(50,10)   # mu 50, stddev 10
np.random.normal(50, 10, (2,2))

array([[ 53.65070414,  41.95090599],
       [ 59.16076265,  53.74587422]])

other 

In [33]:
np.random.binomial(n=100, p=0.5)

51

In [34]:
np.random.poisson(lam=10)

17

In [35]:
np.random.beta(a=3, b=5)

0.7219574387717256